// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFKF5GU-_0mQnG70XoRjSEVVxL_6z4oE',
    appId: '1:823876101682:web:8a7cb5140677a6bc447e2b',
    messagingSenderId: '823876101682',
    projectId: 'pokimon-73cba',
    authDomain: 'pokimon-73cba.firebaseapp.com',
    storageBucket: 'pokimon-73cba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2nBxYwsaDjPdUklTUfkGoHIMRecbvEY',
    appId: '1:823876101682:android:95ebb31b97a80369447e2b',
    messagingSenderId: '823876101682',
    projectId: 'pokimon-73cba',
    storageBucket: 'pokimon-73cba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Is-QfwMf4jZsRIFE-mMIIaefRvJrbVg',
    appId: '1:823876101682:ios:1f054ba5be7a5868447e2b',
    messagingSenderId: '823876101682',
    projectId: 'pokimon-73cba',
    storageBucket: 'pokimon-73cba.appspot.com',
    iosClientId: '823876101682-pnbnnpcntiq3keh9opcvs2qfjl1ref1e.apps.googleusercontent.com',
    iosBundleId: 'com.testing.pokimon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Is-QfwMf4jZsRIFE-mMIIaefRvJrbVg',
    appId: '1:823876101682:ios:1f054ba5be7a5868447e2b',
    messagingSenderId: '823876101682',
    projectId: 'pokimon-73cba',
    storageBucket: 'pokimon-73cba.appspot.com',
    iosClientId: '823876101682-pnbnnpcntiq3keh9opcvs2qfjl1ref1e.apps.googleusercontent.com',
    iosBundleId: 'com.testing.pokimon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqFKF5GU-_0mQnG70XoRjSEVVxL_6z4oE',
    appId: '1:823876101682:web:c02ed72784ad8c29447e2b',
    messagingSenderId: '823876101682',
    projectId: 'pokimon-73cba',
    authDomain: 'pokimon-73cba.firebaseapp.com',
    storageBucket: 'pokimon-73cba.appspot.com',
  );
}
